# Generated by Django 3.2.9 on 2021-11-29 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('icon', models.ImageField(upload_to='icon/')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=10)),
                ('is_playing', models.BooleanField(default=False)),
                ('role', models.CharField(max_length=20)),
                ('photo', models.ImageField(upload_to='photo/')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.team')),
            ],
        ),
    ]
